### ISSUE TITLE
int too long to convert

### ISSUE THREAD

**Issue by horsto** [andrewrk/pyedsdk#2]
I know this is probably a long shot since this repository hasn't undergone any changes in many years, but I just discovered this repository and tried it with the most recent Canon SDK under python3.9. With some small syntax changes (python 2->3) it actually seems to work but I get some errors that I don't quite understand. 
```
Exception ignored on calling ctypes callback function: <function ObjectHandler_py at 0x000001BA3AD47670>
Traceback (most recent call last):
  File "c:\PyEDSDK.py", line 56, in ObjectHandler_py
    DownloadImage(object)
  File "c:\PyEDSDK.py", line 92, in DownloadImage
    Call(edsdk.EdsGetDirectoryItemInfo(image, byref(dirinfo)))
ctypes.ArgumentError: argument 1: <class 'OverflowError'>: int too long to convert
```
Do you have any ideas what it could be and do you maybe have any updated code or idea reference to another python library that interfaces with the Canon SDK? I'd be grateful for some pointers / help! Thanks!

**Comment by hitmany** [comment]
@horsto Hey Bro! Any success with your research?
What is best way to work in Python with Canon cameras you found?
